import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { ThemeProvider } from "styled-components";

import { theme } from "../src/styles/theme";
import { Navbar } from "../src/components/Navbar";
import { Sidebar } from "../src/components/Sidebar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Kinvo Premium</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme.light}>
        <div style={{
          display: 'flex',
          width: '100vw',
          minHeight: '100vh',
          flexDirection: 'column',
          margin: 0
        }}>
          <Navbar />
          <div style={{
            flexGrow: 1,
            display: 'flex',
            flexDirection: 'row',
            alignItems: 'stretch'
          }}>
            <Sidebar />
          </div>
        </div>
      </ThemeProvider>
    </>
  );
};

export default Home;
