import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { ThemeProvider } from "styled-components";

import { theme } from "../src/styles/theme";
import { Navbar } from "../src/components/Navbar";
import { Sidebar } from "../src/components/Sidebar";
import { MainContent } from '../src/components/MainContent';
import { Text } from "../src/components/Text";
import { Flex } from "../src/components/Flex";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Kinvo Premium</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme.light}>
        <Flex direction="column" width="100vw" minHeight="100vh">
          <Navbar />
          <Flex grow direction="row" align="stretch">
            <Sidebar />
            <MainContent>
              <h3>
                <Text color="primary">Renda fixa</Text>
              </h3>
              <Flex direction="row" justify="space-between" gap={1}>
                <div>Test</div>
                <div>Test</div>
                <div>Test</div>
                <div>Test</div>
                <div>Test</div>
                <div>Test</div>
              </Flex>
            </MainContent>
            </Flex>
          </Flex>
      </ThemeProvider>
    </>
  );
};

export default Home;
