import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { ThemeProvider } from "styled-components";

import { theme } from "../src/styles/theme";
import { Navbar } from "../src/components/Navbar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme.light}>
        <Navbar />
      </ThemeProvider>
    </>
  );
};

export default Home;
