import Head from 'next/head'
import TopBar from '../components/TopBar'
import SideBar from '../components/SideBar'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Fundo Renda Fixa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TopBar />
      <div className={styles["content-container"]}>
        <SideBar />

        <main className={styles.main}>
        </main>
      </div>
      {/* <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> */}
    </div>
  )
}
